(define tolerance 0.00001)

(define (fixed-point f first-guess)
  (define (close-enough? v1 v2)
    (< (abs (- v1 v2)) tolerance))
  (define (try n guess)
    (let ((next (f guess)))
      (display n)
      (display ": ")
      (display next)
      (newline)
      (if (close-enough? guess next)
          next
          (try (inc n) next))))
  (display "1: ")
  (display first-guess)
  (newline)
  (try 2 first-guess))
